# Change these first
owner: rikaisolutions # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

delay: 2000
sites:
  - name: Rikai Website
    url: https://www.rikai.ch
    __dangerous__insecure: true
  - name: Rikai App
    url: https://app.rikai.ch
  - name: Home Sampling Website
    url: https://www.homesampling.ch
  - name: Home Sampling App
    url: https://app.rikai.ch
  - name: Invenimus Website
    url: https://www.invenimus.ch

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rikai.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Service Availability"
  introMessage: "Our services"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
